# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Publish to Coveralls
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install coveralls coverage
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f requirements-test.txt ]; then pip install -r requirements-test.txt; fi

      - name: Test with unittest and Coverage.py
        env:
          AD_CLIENT_ID: ${{ secrets.AD_CLIENT_ID }}
          AD_CLIENT_SECRET: ${{ secrets.AD_CLIENT_SECRET }}
          AD_TENANT_ID: ${{ secrets.AD_TENANT_ID }}
          DATABRICKS_REGION: ${{ secrets.DATABRICKS_REGION }}
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        run: |
          coverage run --source azure_databricks_api -m unittest
          coveralls