# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Unit Tests
on:
  push:
    branches: [ main ]
    paths:
      - "azure_databricks_api/**.py"
      - "tests/**.py"
      - ".github/workflows/**.yml"
      - ".coveragerc"
      - "requirements.txt"
      - "requirements-tests.txt"
  
  pull_request:
    branches: [ main ]
    paths:
      - "azure_databricks_api/**.py"
      - "tests/**.py"
      - ".github/workflows/**.yml"
      - ".coveragerc"
      - "requirements.txt"
      - "requirements-tests.txt"

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install coveralls coverage
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f requirements-test.txt ]; then pip install -r requirements-test.txt; fi

      - name: Run Test Suite
        env:
          AD_CLIENT_ID: ${{ secrets.AD_CLIENT_ID }}
          AD_CLIENT_SECRET: ${{ secrets.AD_CLIENT_SECRET }}
          AD_TENANT_ID: ${{ secrets.AD_TENANT_ID }}
          DATABRICKS_REGION: ${{ secrets.DATABRICKS_REGION }}
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          pytest --cov azure_databricks_api --junitxml=junit/test-results.xml tests/
      - name: Upload Coverage Results to Coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        run: |
          coveralls
  test-matrix:
    runs-on: ${{ matrix.os }}
    if: ${{ github.event_name == 'pull_request' }}
    needs: coverage
        
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.6, 3.7, 3.8]
      max-parallel: 1
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-test.txt

    - name: Run Test Suites
      env:
        AD_CLIENT_ID: ${{ secrets.AD_CLIENT_ID }}
        AD_CLIENT_SECRET: ${{ secrets.AD_CLIENT_SECRET }}
        AD_TENANT_ID: ${{ secrets.AD_TENANT_ID }}
        DATABRICKS_REGION: ${{ secrets.DATABRICKS_REGION }}
        PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
      run: |
        pytest --cov azure_databricks_api --junitxml=junit/test-results.xml tests/
